CREATE TABLE IF NOT EXISTS CITY (
  id         INTEGER IDENTITY PRIMARY KEY,
  name VARCHAR(30),
  state  VARCHAR(30),
  country  VARCHAR(30),
  map  VARCHAR(30)
);
TRUNCATE TABLE CITY;
CREATE TABLE IF NOT EXISTS UNO (
  id         INTEGER IDENTITY PRIMARY KEY,
  name VARCHAR(30)
);
TRUNCATE TABLE UNO;
